language: python

python:
  - 3.8

install:
  - pip install -r requirements.txt

# before_script:
#   - python manage.py migrate

# script:
#   - black --check .
#   - flake8 .
#   - coverage run --source=mysite_swe1_app,polls manage.py test

# after_script:
#   - coveralls

# before_deploy: "echo 'Deploying Timenplace from Travis...'"
# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   region: "us-west-2"
#   app: "polls"
#   env: "django-env"
#   bucket_name: "elasticbeanstalk-us-west-2-200959226035"

# only_create_app_version: "true"